backend:
  name: github
  repo: CesarHdez1517/IPBC-netlify
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "articulos"
    label: "Artículos"
    folder: "src/data/articulos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Resumen", name: "excerpt", widget: "text" }
      - { label: "Imagen", name: "imageUrl", widget: "image", required: false }
      - { label: "Fecha", name: "createdAt", widget: "datetime" }
      - { label: "Contenido", name: "content", widget: "markdown" }

  - name: "videos"
    label: "Videos"
    folder: "src/data/videos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "ID YouTube", name: "youtubeId", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text", required: false }